services:
  - docker

before_install:
  - mkdir -p output
  - mkdir -p output/css/
  - mkdir -p output/assets/
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc

after_error:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:
  - cd output ; mv ../index.html index.html ; mv ../css/style.css css/style.css; mv ../css/jquery.min.js css/jquery.min.js; mv ../css/browser.min.js css/browser.min.js; mv ../css/breakpoints.min.js css/breakpoints.min.js; mv ../css/util.js css/util.js; mv ../css/main.js css/main.js; mv ../css/main.css css/main.css; mv ../css/noscript.css css/noscript.css; 
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1