:toc: auto
:toc-position: left
:toclevels: 3

= AdminSys & Networking tools Linux
== LINUX
=== uname ou lsb-release

	Connaitre la version de linux.
	uname -a
	uname -v
	uname -r

	ou

	lsb-release -a

== LINUX Disk
=== ls /mnt

	Lister les partions de disque.

=== less /etc/fstab

	Information sur la partition disque de linux.

=== df

	Connaitre l'espace disque.

	df -ah

== LINUX SYSTEM DEAMON
=== service (old) ou systemctl (new)

	Systemd: Deamon linux gestionnaire du noyau linux.

	service [nomService] status | start | stop
connaitre le status du X service

	systemctl status | start | stop [nomService]
connaitre le status du X service avec la commande systemctl

exemple:

	systemctl status docker
	systemctl status udev

=== top et htop (monitoring process)

	top permet de visualiser la consomation de ressource des processus actives. htop est un outils améliorer de top.

=== ps aux |

	voir les processus en cours d'execution.

== LINUX NETWORK
=== netstat

	Netstat ou Networking Statistique. Il permet de générer une présentation assez complete du reseau.

	netstat -nr
	Affiche la table de routage

	netstat -laputen | grep 80
	Connaitre le port 80

	netstat -tulpen
	sudo netstat -tulpen
	Connaitre un max d'information sur les processus et avec sudo, on affiche les processus impliqués

=== tcpdump

	outils puissant qui permet d'afficher la trame TCP. On peut avoir à l'utiliser pour analyser les failles réseaux, le 3 hands check (SYN,SYN[ACK],ACK)

=== nmap

	nmap est l'accronyme de network map. nmap permet de générer une cartographie de l'adresse ip demandé.
	affiche les détails de port ouvert de l'hote.

	nmap [monIP ou monDomainName]

=== hosts

	hosts est le fichier de configuration de l'hote de la machine en question. Il permet de spécifier le DNS c'est à dire, de definier dans ce fichier /etc/hosts la correspondance entre un ip et un nom de domaine.

	$ /etc/hosts

	[valeur] uri [alias]

	exemple:
	127.0.0.1 localhost

	$ si je veux ajouter exemple xxx.com sur mon ip public:

	-- aller sur network-tools.com/
	-- recupérer un adresse ip
	-- adresseIP_X xxx.com

== Changer le nom de l'ĥote

=== ssh

	Outil permettant d'accéder à une machine distante

=== sftp

=== stat

	acronyme de statisitque de fichier ou du system. Il permet de voir les détails d'un fichier, création, droit, etc.

