:toc: auto
:toc-position: left
:toclevels: 3

= AdminSys & Networking tools for Linux

== LINUX
=== uname ou lsb-release

	Connaitre la version de linux.

.CLI: `uname -a | -v | -r`

.CLI: `lsb-release -a`

== LINUX Disk
=== ls /mnt

-> Lister les partions de disque.

=== less /etc/fstab

-> Information sur la partition disque de linux.

=== df
-> Connaitre l'espace disque.

.CLI: `df -ah`

.CLI: `df -f`

== LINUX SYSTEM DEAMON
=== service (old) ou systemctl (new)

Systemd: Deamon linux gestionnaire du noyau linux.

.CLI: `service [nomService] status | start | stop`
-> connaitre le status du X service

.CLI: `systemctl status | start | stop [nomService]`
-> connaitre le status du X service avec la .CLIe systemctl

.exemple:

.CLI: `systemctl status docker`
.CLI: `systemctl status udev`

=== top et htop (monitoring process)
-> top permet de visualiser la consomation de ressource des processus actives. htop est un outils améliorer de top.

=== ps aux | grep yyy

-> voir les processus en cours d'execution.

== LINUX NETWORK
=== netstat

Netstat ou Networking Statistique. Il permet de générer une présentation assez complete du reseau.

.CLI: `netstat -nr`

    Affiche la table de routage

.CLI: `netstat -laputen | grep 80`

	Connaitre le port 80

.CLI: `netstat -tulpen`

    Connaitre un max d'information sur les processus et avec sudo, on affiche les processus impliqués

=== tcpdump

    outils puissant qui permet d'afficher la trame TCP. On peut avoir à l'utiliser pour analyser les failles réseaux, le 3 hands check (SYN,SYN[ACK],ACK)

=== nmap

nmap est l'accronyme de network map. nmap permet de générer une cartographie de l'adresse ip demandé et affiche les détails de port ouvert de l'hote.

.CLI: `nmap [monIP ou monDomainName]`

=== hosts

`/etc/hosts` est le fichier de configuration de l'hote de la machine en question. Il permet de spécifier le DNS c'est à dire, de definier dans ce fichier /etc/hosts la correspondance entre un ip et un nom de domaine.

.CLI: `/etc/hosts`

./etc/hosts
[NOTE]
===============================
[valeur] uri [alias]
exemple:


127.0.0.1 localhost

192.168.1.10 patsou.ddns.net
===============================


.NB: si je veux ajouter exemple xxx.com sur mon ip public, je fais:

. aller sur `network-tools.com/`
. recupérer un adresse ip
. dans /etc/hosts/
. je rajoute `adresseIP_X xxx.com`

=== ssh : authentification à distance.

Outil permettant d'accéder à une machine distante

.CLI: `ssh-keygen`

Permet de générer une clé `ssh` facilement sur linux. la .CLIe `ssh-keygen -t rsa` est très utile.

.Démarche:
. ssh-keygen -t rsa
. stocker la clé dans $HOME
. voir la description du contenu: `cat ~/.ssh/id_rsa.pub`
. copier la clé sur le serveur:  `ssh-copy-id utilisateur@ipduserveur`
. ssh 'user@ipserveur'

    et c'est bon! :), vous êtes authenfifié en toute securité. :)


=== sftp
Transfert de fichier sécurisé.

=== stat

acronyme de statisitque de fichier ou du system. Il permet de voir les détails d'un fichier, création, droit, etc.

=== less | cat

decrire un fichier.

== LINUX PROCESSUS : lsof (REMPLACE TOUT)
=== lsof
lister les fichiers d'un processus en cours d'execution.

    sudo lsof | head

.exemple: on va voir un processus qui tourne et voir les fichiers qu'il a ouvert

.. on va voir le processus

    sudo nestat -tulpen

.. on va ouvrir le log du programme

    lsof /etc/log/[nomProgramme].log

=== ps VS lsof: binaire des processus?, où sont ils?

    lsof -p [PIDduProcess]| grep log

=== ps VS lsof: connaitre les processus qu'utilise une librairie

    lsof [cheminDuLibrairie]

    mieux que ps :).

.exemple:

    ls -alh /lib/i386-linux-gnu/libgcc_s.so.1
    -rw-r--r-- 1 root root 114K avril  7  2017 /lib/i386-linux-gnu/libgcc_s.so.1

    lsof /lib/i386-linux-gnu/libgcc_s.so.1
    lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/120/gvfs

.sortie:
    .CLI    PID   USER  FD   TYPE DEVICE SIZE/OFF    NODE NAME
    TeamViewe 4603 patsoo mem    REG    8,3   116312 8659775 /lib/i386-linux-gnu/libgcc_s.so.1
    wineserve 5093 patsoo mem    REG    8,3   116312 8659775 /lib/i386-linux-gnu/libgcc_s.so.1
    services. 5137 patsoo mem    REG    8,3   116312 8659775 /lib/i386-linux-gnu/libgcc_s.so.1
    explorer. 5526 patsoo mem    REG    8,3   116312 8659775 /lib/i386-linux-gnu/libgcc_s.so.1
    TVGuiDele 5540 patsoo mem    REG    8,3   116312 8659775 /lib/i386-linux-gnu/libgcc_s.so.1

=== Reseau avec lsof: connaitre les processus ecoutant un protocole

    lsof -i udp

=== connaitre l'espace disque

au lieu de faire `df -f`, on utilise `lsof`

    lsof -f

=== lsof VS htop : monitoring un numéro de processus

    lsof -p [numPID]

.exemple:
    . htop
    . recupérer num PID
    . lsof -p [numPID]

    lsof va décrire tout ce qui se passe sur le PID (les fichiers ouverts, les ports, ...).
