:toc: auto
:toc-position: left
:toclevels: 3

= AdminSys & Networking tools Linux

== Outils en ligne de commande

= top et htop (monitoring process)

top permet de visualiser la consomation de ressource des processus actives. htop est un outils améliorer de top.


= netstat

	accronime de networking statistique. Il permet de générer une présentation assez complete du reseau.

Affiche la table de routage
** netstat -nr

Connaitre le port 80
** netstat -laputen | grep 80

= tcpdump

outils puissant qui permet d'afficher la trame TCP. On peut avoir à l'utiliser pour analyser les failles réseaux, le 3 hands check (SYN,SYN[ACK],ACK)

= nmap

nmap est l'accronyme de network map. nmap permet de générer une cartographie de l'adresse ip demandé.
- affiche les détails de port ouvert de l'hote.

** nmap [monIP ou monDomainName]

= hosts

hosts est le fichier de configuration de l'hote de la machine en question. Il permet de spécifier le DNS c'est à dire, de definier dans ce fichier /etc/hosts la correspondance entre un ip et un nom de domaine.

/etc/hosts

valeur uri alias

exemple:

 127.0.0.1 localhost

$ si je veux ajouter exemple xxx.com sur mon ip public:

- aller sur network-tools.com/
- recupérer un adresse ip
- adresseIP_X xxx.com

== Changer le nom de l'ĥote


= ssh

= sftp

= stat

acronyme de statisitque de fichier ou du system. Il permet de voir les détails d'un fichier, création, droit, etc.

