:toc: auto
:toc-position: left
:toclevels: 3

= Cloud Computing
Patty RANDRIAMBOLOLONA <patty08@github.com>

== Models du cloud computing
=== IaaS
`Hyper convergence` une approche du Datacenter qui rassemble et banalise des fonctions et services dans une même solution.

IaaS (Infrastructure as a Service) propose à l'utilisateur un socle d’infrastructure informatique virtualisé, distribué et en grande partie automatisé. Un tel outil permet de mettre en production des applications utilisées par la DSI ou les services métiers.

Serveurs, réseaux, stockage : le prestataire met au service de la DSI l'ensemble des ressources d'infrastructures nécessaire au fonctionnement d'une application, avec différents niveaux de service.

.Comment?
L’unité de consommation sera la machine virtuelle, équipée de CPU, de mémoire et de stockage. La facturation sera comptabilisée sur le temps d’utilisation, et de sa consommation en nombre d’entrées sorties stockage et réseau.

Le bénéfice ? Ces offres permettent aux DSI de se concentrer sur le développement applicatif sans avoir à gérer des infrastructure, et leurs évolutions.

=== Paas
Pour les développeurs, la mise à disposition d'une plateforme de développement sur une couche initiale d'IaaS permet un gain de temps et des possibilités de test applicatifs, trop complexes à mettre en oeuvre en interne. C'est ce que propose le PaaS (Platform as a Service).

Gestion des machines virtuelles, du middleware, du monitoring : tout est pris en charge de manière à assurer à l'utilisateur un confort d'usage digne de... l'énergie électrique. On appuie sur un bouton, et ça marche.

.SaaS: "Un logiciel sans prise de tête"
Enfin, le SaaS est tout simplement un logiciel mis à disposition à distance par un éditeur. L'utilisateur installe un client sur sa machine pour utiliser la solution, ou y accède via un navigateur web. Il n'a pas a se préoccuper de la plate-forme d’infrastructure ou de la plate-forme logicielle. Là aussi, le client paie l'utilisation de la solution en fonction de sa consommation.

Alternative directe et crédible au mode de déploiement traditionnel de logiciels, il évite à la DSI d'avoir à mettre en place et à exploiter la solution (mise à jour et installation de correctifs entre autres).

=== Docker
==== 1- Comment résumer ce qu'est Docker ?

Docker permet d'embarquer une application dans un container virtuel qui pourra s'exécuter sur n'importe quel machine. D'abord optimisé pour Linux, il l'est désormais pour Windows Server.

C'est une technologie qui a pour but de faciliter les déploiements d'application, et la gestion du dimensionnement de l'infrastructure sous-jacente. Elle est en partie proposée en open source (sous licence Apache 2.0) par une société américaine, également appelée Docker, qui a été lancée par un Français : Solomon Hykes.

==== 2- Quelle différence avec la virtualisation traditionnelle ?

La virtualisation traditionnelle permet, via un hyperviseur, de simuler une ou plusieurs machines physiques, et les exécuter sous forme de machines virtuelles (VM) sur un serveur ou un terminal. Ces VM intègrent elles-mêmes un OS sur lequel les applications qu'elles contiennent sont exécutées. Ce n'est pas le cas du container. Le container fait en effet directement appel à l'OS de sa machine hôte pour réaliser ses appels système et exécuter ses applications. Historiquement, Docker repose sur le format de containers Linux, alias LXC. Il l'étend par le biais d'une API dans l'optique d'exécuter les applications dans des containers standards, qui sont donc portables d'un serveur Linux à l'autre.

Grâce à Docker, il est possible de containériser une application, avec pour chaque couche des containers isolant ses composants. C'est le concept d'architecture de microservices.

==== 3- La technologie Docker est-elle capable de passer à l'échelle sur des architectures en grappe ?

Pour gérer une architecture de containers en cluster, Docker a développé Swarm. L'enjeu : étendre la portabilité, au-delà d'un container unitaire, à toute une architecture de containers en cluster. Docker a parallèlement introduit dans son orchestrateur tous les processus nécessaires à la production à grande échelle (équilibrage de charge, gestion de la résilience, du chiffrement des transactions entre les nœuds...).

Mais en matière de performance, la société de San Francisco veut aller encore plus loin. Elle a acquis début 2016 la start-up Conductant qui s'est illustrée dans le développement d'Apache Aurora.

Un système de clustering qui est conçu pour gérer des applications atteignant des centaines de millions d'utilisateurs. Toujours pour faciliter le déploiement des architectures en container, Docker propose, aussi, une console graphique de pilotage (Docker Universal Control Plane) et des outils de sécurité (notamment Trusted Registry, ou Docker Secrets qui gère l'intégrité d'un container tout au long de son cycle de vie).

Toutes ces briques s'inscrivent dans une plateforme dite de Containers as a Service (CaaS), baptisée Docker Datacenter (DDC), visant à assurer le pilotage complet d'un cloud orienté containers (en recouvrant les processus de build, ship et run). Enfin, Docker a aussi acquis fin 2014 la plateforme cloud Tutum : un environnement SaaS conçu pour piloter le déploiement d'applications containerisées sur divers clouds publics (Microsoft Azure, Digital Ocean, Amazon Web Services et IBM SoftLayer).

==== 4- Quels sont les composants proposés par Docker en open source ?

Docker a publié une dizaine de composants sous licence Apache (voir le graphique ci-dessous). Des composants qui recouvrent les principales fonctionnalités nécessaires au pilotage d'une architecture containérisée :

	- `gestion du réseau`,
	- `du stockage, de la sécurité`... Parmi eux figure `containerd`.

Une brique centrale de la technologie Docker puisqu'elle permet l'exécution du container. Considérant la criticité de cette brique en vue de la standardisation des offres de container, Docker en a reversé les droits à une organisation indépendante (la Cloud Native Computing Foundation). En avril 2017, l'éditeur est allé un peu plus loin dans la démarche en lançant Moby : un framework open source dessiné pour construire des systèmes de container. Il comprend 80 composants open source : ceux de Docker (containerd, swarmkit...) mais aussi d'autres projets (Redis, Nginx...). Moby se veut être un projet participatif, à travers lequel tous les acteurs de la communauté Docker construisant des solutions à base de container peuvent partager des briques.

=== Surikator (mon projet open source Docker)

Le projet nommé `Surikator` est une PaaS open source développée en langage Go, conteneurisé dans un container docker linux. Surikator en un mot est un middleware qui mesure les ressources systèmes, les métriques et les logs d’un container docker pour produire un monitoring.

La réalisation du projet a demander une maitrise sur les technologies nouvelles tel que :

    . Une compétence sur Docker,
    . Go langage (Google),
    . Bonne compétence en Linux, notamment Ubuntu,
    . Script Bash,
    . Et les outils d’intégration, notamment Jenkins.

Le développement du projet en tant que service se repose sur l’approche diviser pour mieux régner dans le but de pouvoir apporter une optimisation à l’avenir sans avoir à impacter le reste du code. Pour cela, Surikator est décomposé en trois microservice distincts, dont chaque microservice à son propre rôle, dont:

   . Amélioration de l’évaluation de la performance des processus et de l’aptitude à at-teindre les objectifs notamment sur les tests effectués,
   . Amélioration de l’efficacité et de l’efficience opérationnelles,
   . Plus grande aptitude à passer en revue, remettre en question et changer les opi-nions et les décisions,
   . Plus grande aptitude à démontrer l’efficacité de décisions antérieures,
   . Prendre des décisions et entreprendre des actions fondées sur des preuves, tout en tenant compte de l’expérience et de l’intuition.

[ENGLISH]

= Azure Vs AWS Vs Google Cloud

As per the Gartner Survey Report, the market of public cloud is estimated to hit a total worth of $411 bn by 2020. Cloud technology is used for making backups, storing data, working in co-op, and whatnot.

Microsoft Azure claims more than 95 percent of Fortune 500 companies use Azure while 62% of market is captured by Amazon Web Services. Microsoft Azure almost doubled their revenues in year 2017 that is approximately $1.5 billion, while Amazon Web Services claims approximately to $9.7 billion which is 45% increase in revenue. AWS revenues increased by nearly three times as much as Azure´s revenue. Google hasn’t reported its cloud revenue for 2018, yet, but Canalys estimates Google’s cloud revenue at $6.8 billion, representing annual growth of 94%. That secures Google’s spot for the third highest market share. According to Google and Alphabet CFO Ruth Porat, “Google Cloud Platform remains one of the fastest growing businesses in Alphabet with strong customer momentum reflected in particular in demand for our compute and data analytics products”.

== Microsoft Azure:

Microsoft Azure, formerly known as Windows Azure and stands out as one of the top vendors in the market with a wide range of services available. Azure is Microsoft’s public cloud computing platform. It was commercially launched from year 2010. Today it is available to 54 regions, spread across 140 countries. Azure has more than 100 services with great end-to-end tools. 120000 new customer subscription per month. Microsoft offers all three of the major categories of cloud computing, platform as a service (PaaS), software as a service (SaaS) and infrastructure as a service (IaaS). It deals with PaaS and IaaS offerings under the brand name of Microsoft Azure.

== Amazon Web Services:

Amazon Web Services (AWS) started in year 2006 and today AWS Cloud spans 57 Availability Zones within 19 geographic Regions around the world, with announced plans for 15 more Availability Zones and five more Regions in Bahrain, Cape Town, Hong Kong SAR, Milan, and Stockholm. AWS is a comprehensive, evolving cloud computing platform provided by Amazon.  It provides cloud platform as a Infrastructure as a Service (IaaS), Software as a Service (SaaS) and Platform as a service (SaaS). It provide Infrastructure as a Service (IaaS) into five different categories of Storage, Compute, Database, Content Delivery and Networking. AWS was the first company to offer pay-as-you-go cloud computing model.

== Google Cloud Platform:

Google Cloud Platform (GCP) started their journey on October 6, 2011. At the time of this article, they’ve had 5 years during which they’ve managed to create a good presence in the industry. Initially, the push was to strengthen their own services, such as Google or YouTube. But they went further and created enterprise services, so now anyone can use their cloud platform. Google Cloud Platform, as the name implies, is a cloud computing platform that provides infrastructure tools and services for users to build applications and services on top of. Google Cloud Platform (GCP) is a portfolio of cloud computing services that grew around the initial Google App Engine framework for hosting web applications from Google’s data centers.


.Key Differences between Azure Vs AWS Vs Google Cloud
[options="header,footer"]
|=======================
| Google Cloud Platform         |       Microsoft Azure                     |        Amazon Web Services
|Platform As A Service          | GCP supports Google App Engine            | Azure supports Cloud Services  | AWS supports Elastic Beanstalk
|Instances Family               | GCP supports 7    | Azure support 4       | AWS support 7
|Instance Types                 | Maximum 18        | Maximum up to 33      | Maximum up to 38
|Caching                        | CloudCDN          | Azure supports Redis Cache     | ASW supports Elastic Cache
|Data Warehouse                 |                   | Azure Supports SQL Data Warehouse     | ASW supports Redshift
|Virtual Networking             |                   | Virtual Network       | Virtual Private Cloud
|Administration                 | Cloud Console	    | Log Analytics, Operations Management Suite, Resource Health, Storage Explorer     | Application Discovery Service, System manager, Personal Health Dashboard
|Pricing                        | Per Minute        | For Infrastructure pay Per Minute    | For Infrastructure pay Per Hour
|Big Data Platform              | Widely used as a Big data Platform  | Less mature comparing AWS for Big Data environment     | More  mature for Big Data environment
|Hadoop                         | HDInsight         |    | Elastic Map Reduce
|NoSQL Databases                | Cloud Bigtable    | Azure Document DB    | Amazon Dynamo DB
|Object Size Limits             | 5 TB              | 4.75 TB     | 5 TB
|How much platform are Matured  | GCP are 7 years old     | Azure are 8 years old     | AWS are 18 years old
|Market Capture                 | 12% of Cloud Market    | 20% of entire cloud market   | 62% of entire cloud market
|Maximum Processor in VM        | 96                | 128  | 128
|Maximum Memory in VM           | 1433 GB           | 3800 GB    | 3904 GB
|SAL Availability               | 99.95% Monthly Uptime    | 99.90%   | 99.95%
|Operating System Supported     | Windows, SLES, CentOS, CoreOS, OpenSUSE, RHEL, Debian, FreeBSD, Ubunyu     | RHEL, OpenSUSE, Windows, SLES, CoreOS, CentOS, Cloud Linux, Debian FreeBSD, Ubuntu, Oracle Linux  | RHEL, Ubuntu, Oracle Linux, Cloud Linux, CentOS, Windows, SLES, Windows, FreeBSD, Debian, CoreOS
|Platform	Cloud computing platform that provides infrastructure tools and services     | Public Cloud Platform for Microsoft   | On demand cloud computing platform for Amazon Web Services
|Open Source Community          | Not much open source tool supported     | Not much open source tool supported   | Large number of Open Source Tool Supported
|Marketplace                    | G suite Marketplace   | Azure Marketplace   | AWS Marketplace
|App Testing                    | Cloud Test lab is being used in this  | DevTest labs are being used    | Device farm is being used
|File Storage                   | ZFS and Avere    | Azure Files  | EFS
|=======================

.Pros and Cons between Cloud Service Provider ( Azure Vs AWS Vs Google Cloud ):
[options="header,footer"]
|=======================
| Cloud Service Provider |              Advantages                      |           Disadvantages
| Amazon Web Services	 |  ·  Dominant market position                     · Difficult to use
|                           ·  Extensive, mature offerings                  · Cost management
|                           ·  Support for large organizations              · Overwhelming options
|                           ·  Extensive training
|                           ·  Global reach
| Microsoft Azure	     |  · Second largest provider                   |   · Issues with documentation
|                           · Integration with Microsoft tools and software · Incomplete management tooling
|                           · Broad feature set
|                           · Hybrid cloud
|                           · Support for open source
| Google Cloud Platform	 |  · Designed for cloud-native businesses      |   ·  Late entrant to IaaS market
|                           ·  Commitment to open source and portability    ·  Fewer features and services
|                           ·  Deep discounts and flexible contracts        ·  Historically not as enterprise focused
|                           ·  DevOps expertise
|=======================

== And at the Bottom: ( Azure Vs AWS Vs Google Cloud )

We are generating very huge volume of data and everyday data are piling up. Most of the data are stored in cloud and it opened door of more growth and business opportunities to cloud vendors. With the exponentially growth and demand of Cloud Technology, public cloud vendor are in very high demands.

So, in this blog, we had a Cloud Services comparison for Azure Vs AWS Vs Google. I have described comparison in terms of different services offered by these public clouds, market share, and pricing. But the actual research while choosing the best cloud service provider depends on what you need and what the provider offers. Comparing cloud services can be a tough task but this comparison only scratches the surface and is meant for people who are getting started with cloud computing. If you would like to go to with the safest option, Amazon AWS is the best way to go. If your application utilizes Microsoft products or languages, Azure can help you sustain and take advantage of Microsoft’s ecosystem. GCP stands in a sweet spot and is viable most of the time. This battle cloud between AWS, Google, and Azure makes us conclude that whatever cloud service you will opt, you will be happy. Due to the competition, all the cloud service providers are trying to attract customers with the extended services at reduced prices.

When evaluating cloud platforms, it’s important to keep their strengths and weaknesses in mind. However, it’s equally as important to understand where providers put the most attention into developing and maintaining.