:toc: auto
:toc-position: left
:toclevels: 3

= Jenkins and GitLab configurations trigger build
This document is a step by step configuration in order to activate automatique build on all behavior of GitLab. This setting is a trigger to multibranch job configuration, all modication on GitLab implies automatic build in CloudUni/Jenkins.
    `id: johndoe`
    `pwd: abc2015`
hello
== Create a GitLab key

Jenkins need the access token to listen to GitLab behaviors.
1. go to Profile Settings
2. Access Todkens
3. Add a Personnal Access Token
    `name: cloudunit`
    `Expire at: xxx`

`xxx` : leave it blanc to set it never or give expiration date.
`[important]`: don't forget to save the token ID.

== Jenkins file configuration
1. in your project, make sure that you have Jenkins file
2. open your Jenkinsfile
3. add athe first line a GitLab Jenkins plugin properties
    `properties([gitLabConnection('cloudunit')])`

== Jenkins configuration
=== Requirement
 - Jenkins version 2.46.1 (Tested)

=== GitLab Jenkinsfile
1. go to Jenkins management
2. system configuration
3. got to Gitlab panel
    `1. Connection name: cloudunit`
    `2. Gitlab host URL: https://gitlab-cu02.cloudunit.io/`
    `3. Credentials: Jenkins`  go to How to add credentials
    `4. Add button`
4. Save button
Make sure that you have credentials token, go to `Identities`

=== How to add credentials
In the Jenkins Credentials Provider: Jenkins,
  `1. Domain: Global identity`
  `2. Domain: GitLab API token`
  `3. Scope: Global`
  `4. API token	: Paste TOKEN ID HERE`
  `5. ID: cloudunit`
  `6. Description: My cloudunit GitLab/Jenkins`
  `7. Add`
