:toc: auto
:toc-position: left
:toclevels: 3

= REGEX
Patty RANDRIAMBOLOLONA <patty08@github.com>

== 1. Syntax
l'expression regulière repond à la question dont: "quelle occurence tu cherches dans une suite de char"

afficher expression regulière

- https://regexper.com


    - (aa)? : La variable contient une fois au maximum la chaine « aa »
    - (aa)+ : La variable contient une fois au minimum la chaine « aa »
    - (aa)* : La variable contient zéro ou plusieurs fois la chaine « aa »
    - (aa){2} : La variable contient 2 chaine « aa » qui se suivent
    - (aa){2,5} : La variable contient entre 2 et 5 fois la chaine « aa » qui se suivent

    - \d represente les nombres
    - \D represente autre choses que les nombres
    - \s represente les espaces
    - \S represente autre choses que les espaces
    - \w represente les caractères
    - \W represente autre choses que les caractères
    -  ? au moins une fois
    -  * 0 ou plusieurs fois
    -  {n} n nombre de fois

.exemple: 123 patty

    \[1-5]\s\[a-z]

.adresse e-mail 

    ^[a-zA-Z]+@[a-zA-Z]+\.[a-zA-Z]{2,6}$

.tester un email

    ^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$

.tester une url

    ^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$

.tester une adresse ip

    ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$

.récupérer le contenu entre deux balises strong (à adapter, en php utilisez preg_match_all )

    ^(.*)$

.tester un code postale

    ^((0[1-9])|([1-8][0-9])|(9[0-8])|(2A)|(2B))[0-9]{3}$

.tester sur le texte fait bien entre 4 et 128 caractères

    ^(.){4,128}$

.tester un numéro de téléphone français (06 01 02 03 04)

    ^0[1-68]([-. ]?[0-9]{2}){4}$

.tester un numéro de téléphone américain (333-333-3333)

    ^[0-9]{3,3}[-]{1,1}[0-9]{3,3}[-]{1,1}[0-9]{4,4}$

.tester un numéro de téléphone anglais (01614840484)

    ^[0-9]{11,11}$

.tester un code postale anglais (55416)

    ^[0-9]{5,5}$

.tester un code postale américain (AL42PT)

    ^[A-Z]{1,2}([0-9]{1,2}|[0-9]{1,1}[A-Z]{1,1})( |)[0-9]{1,1}[A-Z]{2,2}$

.tester une adresse IP V6
  
  ^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:)))(%.+)?s*$
